FROM pandoc/ubuntu:2.13

WORKDIR /data

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -q --no-allow-insecure-repositories update \
	&& apt-get install --assume-yes --no-install-recommends \
		ruby \
		ruby-dev \
		gcc \
		make \
		libc6-dev \
		python3-pip \
		git \
	&& rm -rf /var/lib/apt/lists/*

RUN pip3 install \
		bibtexparser==1.2.0 \
		langid==1.1.6 \
		git+https://github.com/sergiocorreia/panflute.git@a253315d5ae64018ea9c3ccbd4d5aec26b374a48#egg=panflute

# panflute 2.1.0 is not yet on pypi.
# remember to remove git from apt above when this is resolved.

RUN gem install anystyle-cli

COPY . /data
ENTRYPOINT ["/data/convert_docx2md.sh"]
